name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: adopt
          java-version: 17

      - name: Prepare environment
        env:
          SIGNING_SECRET_KEY_RING_FILE: ${{ vars.SIGNING_SECRET_KEY_RING_FILE }}
          OSSRH_USERNAME: ${{ vars.OSSRH_USERNAME }}
          GPG_KEY_NAME: ${{ vars.GPG_KEY_NAME }}

        # Builds the release artifacts of the library
      - name: Release build
        run: ./gradlew build
